import '../globals.css'
import { Inter } from 'next/font/google'
import LandingLayout from '../(components)/LandingLayout'
import PagesLayout from '../(components)/PagesLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Demo Next New',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  content,
  sidebar
}: {
  children: React.ReactNode,
  content: React.ReactNode,
  sidebar: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PagesLayout children={children} content={content} sidebar={sidebar}  />
      </body>
    </html>
  )
}
