import '../globals.css'
import { Inter } from 'next/font/google'
import PagesLayout from '../(components)/PagesLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Demo Next New',
  description: 'Generated by create next app',
}

export default function RootLayout({
  content,
  sidebar
}: {
  content: React.ReactNode,
  sidebar: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PagesLayout sidebar={sidebar} content={content}/>
      </body>
    </html>
  )
}
