import '../globals.css'
import { Inter } from 'next/font/google'
import LandingLayout from '../(components)/LandingLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Demo Next New',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LandingLayout>
          {children}
        </LandingLayout>
      </body>
    </html>
  )
}
